import { TableEntry, WorldTrait } from '../types';

export interface TravelEventEntry {
    id: string;
}

export const STARSHIP_TRAVEL_EVENTS_TABLE: TableEntry<TravelEventEntry>[] = [
    { roll_range: [1, 7], value: { id: 'asteroids' } },
    { roll_range: [8, 12], value: { id: 'navigation_trouble' } },
    { roll_range: [13, 17], value: { id: 'raided' } },
    { roll_range: [18, 25], value: { id: 'deep_space_wreckage' } },
    { roll_range: [26, 29], value: { id: 'drive_trouble' } },
    { roll_range: [30, 38], value: { id: 'down_time' } },
    { roll_range: [39, 44], value: { id: 'distress_call' } },
    { roll_range: [45, 50], value: { id: 'patrol_ship' } },
    { roll_range: [51, 53], value: { id: 'cosmic_phenomenon' } },
    { roll_range: [54, 60], value: { id: 'escape_pod' } },
    { roll_range: [61, 66], value: { id: 'accident' } },
    { roll_range: [67, 75], value: { id: 'travel_time' } },
    { roll_range: [76, 85], value: { id: 'uneventful_trip' } },
    { roll_range: [86, 91], value: { id: 'time_to_reflect' } },
    { roll_range: [92, 95], value: { id: 'time_to_read_a_book' } },
    { roll_range: [96, 100], value: { id: 'locked_in_library' } },
];

export const WORLD_TRAITS_TABLE: TableEntry<WorldTrait>[] = [
    { roll_range: [1, 3], value: { id: 'haze', nameKey: 'worldtraits.haze.name', descriptionKey: 'worldtraits.haze.desc' } },
    { roll_range: [4, 6], value: { id: 'overgrown', nameKey: 'worldtraits.overgrown.name', descriptionKey: 'worldtraits.overgrown.desc' } },
    { roll_range: [7, 8], value: { id: 'warzone', nameKey: 'worldtraits.warzone.name', descriptionKey: 'worldtraits.warzone.desc' } },
    { roll_range: [9, 10], value: { id: 'heavily_enforced', nameKey: 'worldtraits.heavily_enforced.name', descriptionKey: 'worldtraits.heavily_enforced.desc' } },
    { roll_range: [11, 12], value: { id: 'rampant_crime', nameKey: 'worldtraits.rampant_crime.name', descriptionKey: 'worldtraits.rampant_crime.desc' } },
    { roll_range: [13, 14], value: { id: 'invasion_risk', nameKey: 'worldtraits.invasion_risk.name', descriptionKey: 'worldtraits.invasion_risk.desc' } },
    { roll_range: [15, 16], value: { id: 'imminent_invasion', nameKey: 'worldtraits.imminent_invasion.name', descriptionKey: 'worldtraits.imminent_invasion.desc' } },
    { roll_range: [17, 18], value: { id: 'lacks_starship_facilities', nameKey: 'worldtraits.lacks_starship_facilities.name', descriptionKey: 'worldtraits.lacks_starship_facilities.desc' } },
    { roll_range: [19, 20], value: { id: 'easy_recruiting', nameKey: 'worldtraits.easy_recruiting.name', descriptionKey: 'worldtraits.easy_recruiting.desc' } },
    { roll_range: [21, 22], value: { id: 'medical_science', nameKey: 'worldtraits.medical_science.name', descriptionKey: 'worldtraits.medical_science.desc' } },
    { roll_range: [23, 24], value: { id: 'technical_knowledge', nameKey: 'worldtraits.technical_knowledge.name', descriptionKey: 'worldtraits.technical_knowledge.desc' } },
    { roll_range: [25, 26], value: { id: 'opportunities', nameKey: 'worldtraits.opportunities.name', descriptionKey: 'worldtraits.opportunities.desc' } },
    { roll_range: [27, 29], value: { id: 'booming_economy', nameKey: 'worldtraits.booming_economy.name', descriptionKey: 'worldtraits.booming_economy.desc' } },
    { roll_range: [30, 32], value: { id: 'busy_markets', nameKey: 'worldtraits.busy_markets.name', descriptionKey: 'worldtraits.busy_markets.desc' } },
    { roll_range: [33, 34], value: { id: 'bureaucratic_mess', nameKey: 'worldtraits.bureaucratic_mess.name', descriptionKey: 'worldtraits.bureaucratic_mess.desc' } },
    { roll_range: [35, 36], value: { id: 'restricted_education', nameKey: 'worldtraits.restricted_education.name', descriptionKey: 'worldtraits.restricted_education.desc' } },
    { roll_range: [37, 38], value: { id: 'expensive_education', nameKey: 'worldtraits.expensive_education.name', descriptionKey: 'worldtraits.expensive_education.desc' } },
    { roll_range: [39, 41], value: { id: 'travel_restricted', nameKey: 'worldtraits.travel_restricted.name', descriptionKey: 'worldtraits.travel_restricted.desc' } },
    { roll_range: [42, 43], value: { id: 'unity_safe_sector', nameKey: 'worldtraits.unity_safe_sector.name', descriptionKey: 'worldtraits.unity_safe_sector.desc' } },
    { roll_range: [44, 46], value: { id: 'gloom', nameKey: 'worldtraits.gloom.name', descriptionKey: 'worldtraits.gloom.desc' } },
    { roll_range: [47, 48], value: { id: 'bot_manufacturing', nameKey: 'worldtraits.bot_manufacturing.name', descriptionKey: 'worldtraits.bot_manufacturing.desc' } },
    { roll_range: [49, 51], value: { id: 'fuel_refinery', nameKey: 'worldtraits.fuel_refinery.name', descriptionKey: 'worldtraits.fuel_refinery.desc' } },
    { roll_range: [52, 53], value: { id: 'alien_species_restricted', nameKey: 'worldtraits.alien_species_restricted.name', descriptionKey: 'worldtraits.alien_species_restricted.desc' } },
    { roll_range: [54, 55], value: { id: 'weapon_licensing', nameKey: 'worldtraits.weapon_licensing.name', descriptionKey: 'worldtraits.weapon_licensing.desc' } },
    { roll_range: [56, 57], value: { id: 'import_restrictions', nameKey: 'worldtraits.import_restrictions.name', descriptionKey: 'worldtraits.import_restrictions.desc' } },
    { roll_range: [58, 59], value: { id: 'military_outpost', nameKey: 'worldtraits.military_outpost.name', descriptionKey: 'worldtraits.military_outpost.desc' } },
    { roll_range: [60, 62], value: { id: 'dangerous', nameKey: 'worldtraits.dangerous.name', descriptionKey: 'worldtraits.dangerous.desc' } },
    { roll_range: [63, 64], value: { id: 'shipyards', nameKey: 'worldtraits.shipyards.name', descriptionKey: 'worldtraits.shipyards.desc' } },
    { roll_range: [65, 67], value: { id: 'barren', nameKey: 'worldtraits.barren.name', descriptionKey: 'worldtraits.barren.desc' } },
    { roll_range: [68, 69], value: { id: 'vendetta_system', nameKey: 'worldtraits.vendetta_system.name', descriptionKey: 'worldtraits.vendetta_system.desc' } },
    { roll_range: [70, 72], value: { id: 'free_trade_zone', nameKey: 'worldtraits.free_trade_zone.name', descriptionKey: 'worldtraits.free_trade_zone.desc' } },
    { roll_range: [73, 74], value: { id: 'corporate_state', nameKey: 'worldtraits.corporate_state.name', descriptionKey: 'worldtraits.corporate_state.desc' } },
    { roll_range: [75, 76], value: { id: 'adventurous_population', nameKey: 'worldtraits.adventurous_population.name', descriptionKey: 'worldtraits.adventurous_population.desc' } },
    { roll_range: [77, 79], value: { id: 'frozen', nameKey: 'worldtraits.frozen.name', descriptionKey: 'worldtraits.frozen.desc' } },
    { roll_range: [80, 81], value: { id: 'flat', nameKey: 'worldtraits.flat.name', descriptionKey: 'worldtraits.flat.desc' } },
    { roll_range: [82, 84], value: { id: 'fuel_shortage', nameKey: 'worldtraits.fuel_shortage.name', descriptionKey: 'worldtraits.fuel_shortage.desc' } },
    { roll_range: [85, 86], value: { id: 'reflective_dust', nameKey: 'worldtraits.reflective_dust.name', descriptionKey: 'worldtraits.reflective_dust.desc' } },
    { roll_range: [87, 89], value: { id: 'high_cost', nameKey: 'worldtraits.high_cost.name', descriptionKey: 'worldtraits.high_cost.desc' } },
    { roll_range: [90, 91], value: { id: 'interdiction', nameKey: 'worldtraits.interdiction.name', descriptionKey: 'worldtraits.interdiction.desc' } },
    { roll_range: [92, 93], value: { id: 'null_zone', nameKey: 'worldtraits.null_zone.name', descriptionKey: 'worldtraits.null_zone.desc' } },
    { roll_range: [94, 96], value: { id: 'crystals', nameKey: 'worldtraits.crystals.name', descriptionKey: 'worldtraits.crystals.desc' } },
    { roll_range: [97, 100], value: { id: 'fog', nameKey: 'worldtraits.fog.name', descriptionKey: 'worldtraits.fog.desc' } },
];