import { MissionOffer, Campaign, PatronType, DangerPay, TimeFrame, Benefit, Hazard, Condition } from '../../types';
import { MISSION_DEFINITIONS } from '../../constants/missions';
import { rollD10 } from '../utils/rolls';
import { PATRON_TABLE, DANGER_PAY_TABLE, TIME_FRAME_TABLE, BHC_TABLE, BENEFITS_SUBTABLE, HAZARDS_SUBTABLE, CONDITIONS_SUBTABLE } from '../../constants/jobs';

const resolve1D10Table = <T>(table: { range: [number, number], value: T }[], roll: number): T => {
    const entry = table.find(e => roll >= e.range[0] && roll <= e.range[1]);
    if (!entry) {
      console.warn(`No table entry found for D10 roll ${roll}.`);
      return table[0].value;
    }
    return entry.value;
};


export const generateJobOffers = (campaign: Campaign): MissionOffer[] => {
    const offers: MissionOffer[] = [];
    
    // Default to 1 offer if none are generated by tasks.
    const numOffersToGenerate = campaign.patronJobsToGenerate || 1;
    const hasCorporateState = campaign.currentWorld?.traits.some(t => t.id === 'corporate_state');

    for (let i = 0; i < numOffersToGenerate; i++) {
        // Step 1: Patron
        let patronInfo;
        if (hasCorporateState) {
            patronInfo = PATRON_TABLE.find(p => p.value.type === 'corporation')!.value;
        } else {
            const patronRoll = rollD10();
            patronInfo = resolve1D10Table(PATRON_TABLE, patronRoll);
        }
        const patronType = patronInfo.type;

        // Step 2: Danger Pay
        const dangerPayRoll = rollD10() + patronInfo.dangerPayBonus;
        const dangerPay = resolve1D10Table(DANGER_PAY_TABLE, dangerPayRoll);

        // Step 3: Time Frame
        const timeFrameRoll = rollD10() + patronInfo.timeFrameBonus;
        const timeFrame = resolve1D10Table(TIME_FRAME_TABLE, timeFrameRoll);
        
        // Step 4: BHC
        const bhcThresholds = BHC_TABLE[patronType];
        let benefit: Benefit | undefined;
        let hazard: Hazard | undefined;
        let condition: Condition | undefined;

        if (rollD10() >= bhcThresholds.benefits) {
            benefit = resolve1D10Table(BENEFITS_SUBTABLE, rollD10());
        }
        if (rollD10() >= bhcThresholds.hazards) {
            hazard = resolve1D10Table(HAZARDS_SUBTABLE, rollD10());
        }
        if (rollD10() >= bhcThresholds.conditions) {
            condition = resolve1D10Table(CONDITIONS_SUBTABLE, rollD10());
        }

        // Pick a mission
        const missionDef = MISSION_DEFINITIONS[Math.floor(Math.random() * MISSION_DEFINITIONS.length)];

        offers.push({
            id: `job_${Date.now()}_${i}`,
            missionType: missionDef.type,
            titleKey: missionDef.titleKey,
            descriptionKey: missionDef.descriptionKey,
            patronType,
            dangerPay,
            timeFrame,
            benefit,
            hazard,
            condition,
        });
    }
    return offers;
};